server:
  port: 8080

spring:
  application:
    name: kata-api

catalog:
  api:
    url: http://localhost:8080/mock/catalogue/produits

logging:
  level:
    com.kata.shopping: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
